export const JeddahNorth = [
  { name: 'الصفا', value: 'Al Safa' },
  { name: 'الروضة', value: 'Al Rawda' },
  { name: 'الخالدية', value: 'Al Khaledaya' },
  { name: ' المرجان', value: 'Al Morgan' },
  { name: 'المروى', value: 'Al-Marwa' },
  { name: 'الفيصلية', value: 'Al Faisaliyah' },
  { name: 'الربوة', value: 'Al Rabwa' },
  { name: 'النزهة', value: 'Al Nozha' },
  { name: 'البوادي', value: 'Al-Bawadi' },
  { name: 'الشاطئ', value: 'Al Shateea' },
  { name: 'الزهرة', value: 'Al Zahrah' },
  { name: 'السلامة ', value: 'Al Salamah' },
  { name: 'النعيم', value: 'Al Naeem' },
  { name: 'النهضة', value: 'Al Nahda' },
  { name: 'المحمدية', value: 'Al Mohamadeya' },
  { name: 'أبحر الشمالي والجنوبي', value: 'Obhur North and southern' },
  { name: 'البساتين', value: 'Al Basatein' },
];

export const JeddahSouth = [
  {
    name: 'حي الامير فواز الشمالي والجنوبي',
    value: 'Prince Fawaz, north and south',
  },
  {
    name: 'حي الأمير عبدالمجيد النموذجي الاسكان الجنوبي',
    value: 'Prince Abdul Majeed, southern housing',
  },
  { name: 'مدائن الفهد', value: "Mada'in Al Fahad" },
  { name: 'الواحة', value: 'Al Waha' },
  { name: 'الحرازات', value: 'Al-Harazat' },
  { name: 'بترومين الكرنتينا', value: 'Petromin Karantina' },
  { name: 'الثعالبة', value: 'Al Saalba' },
  { name: 'الهنداوية', value: 'Al Hinduism' },
  { name: 'غليل', value: 'Galel' },
  { name: 'القريات', value: 'Qurayyat' },
  { name: 'السبيل', value: 'Al Sabeel' },
  { name: 'النزلة اليمانية', value: 'The Yemeni Al-Nazla' },
  { name: 'النزلة الشرقية', value: 'Al-Nazla Al-Sharqiya' },
  { name: 'المنتزهات', value: 'Al Montazahat' },
  { name: 'الاجاويد', value: 'Al Ajaweed' },
  { name: 'السنابل', value: 'Al Sanabel' },
  { name: 'الروابي', value: 'Al Rawaby' },
  { name: 'كيلو ١٤', value: 'Kilo 14' },
  { name: 'العدل', value: 'Al Adl' },
  { name: 'المحجر', value: 'Al Mahgar' },
  { name: 'الكندرة', value: 'Al Kandara' },
  { name: 'الوزيرية', value: 'Al Wazereya' },
  { name: 'الجوهرة', value: 'Al Gawharah' },
];

export const JeddahEast = [
  { name: 'الأجواد', value: 'Al-Ajwad' },
  { name: 'المنار', value: 'Al-Manar' },
  { name: 'الملك فهد', value: 'King Fahd' },
  { name: 'السامر', value: 'Al Samer' },
];

export const JeddahMiddle = [
  { name: 'الحمراء', value: 'Al Homra' },
  { name: 'الورود', value: 'Al Werood' },
  { name: 'الروابي', value: 'Al Rawaby' },
  { name: 'الصحيفة', value: 'Al Sahefa' },
  { name: 'العمارية', value: 'Al Amayra' },
  { name: 'البلد', value: 'Al Balad' },
  { name: 'البغدادية الشرقية والغربية', value: 'Eastern and Western Baghdad' },
  { name: 'الجامعة', value: 'Al Gameaa' },
  { name: 'الثغر', value: 'Al Sagr' },
  { name: 'السليمانية', value: 'Al Sulaymaniyah' },
  { name: 'النسيم', value: 'Al Nassiem' },
  { name: 'بني مالك', value: 'Ibn Malek' },
  { name: 'الرحـاب', value: 'Al Rehab' },
  { name: 'الفيحاء', value: 'Al Fayhaa' },
  { name: 'البغدادية', value: 'Al Bagdadeya' },
  { name: 'الشرفية', value: 'Al Sharafeya' },
  { name: 'الرويس', value: 'Al Royess' },
  { name: 'مشرفة', value: 'Mashrafa' },
  { name: 'العزيزية', value: 'Al Azizah' },
  { name: 'الأندلس', value: 'Al Andalos' },
  { name: 'النخيل ( إبرق الرغامة )', value: 'Al-Nakhil (Ibraq Al-Raghamah)' },
];
