export const Mecca = [
  { name: 'العوالي', value: 'Al Awali' },
  { name: 'الشوقية', value: 'Al Shawqeya' },
  { name: 'وادي جليل', value: 'Jalil Valley' },
  { name: 'ريع ذاخر', value: 'Rea Zakhr' },
  { name: 'جرهم', value: 'Gorhom' },
  { name: 'النوارية', value: 'Al Nawaryah' },
  { name: 'الملك فهد', value: 'King Fahd' },
  { name: 'المرسلات', value: 'Al-Mursalat' },
  { name: 'العكيشية', value: 'Al Akishiya' },
  { name: 'الطندباوي', value: 'Al-Tandbawi' },
  { name: 'الشرائع', value: 'Al Sharaea' },
  { name: 'الزهراء', value: 'Al Zahraa' },
  { name: 'الرصيفة', value: 'Al Rusifa' },
  { name: 'الحمراء وام الجود', value: 'Al-Hamra and Umm Al-Jude' },
  { name: 'الجامعة', value: 'Al Gamaa' },
  { name: 'البيبان', value: 'Al Bayaan' },
  { name: 'العزيزية', value: 'Al Azizah' },
  { name: 'بطحاء قريش', value: 'Batha Quraish' },
  { name: 'كدي', value: 'Kedi' },
  { name: 'حارة الباب والشامية', value: 'Haret Al-Bab and Shamiya' },
  { name: 'الهنداوية', value: 'Al Hinduism' },
  { name: 'النسيم', value: 'Al Nassiem' },
  { name: 'المعابدة', value: 'Al Moabadah' },
  { name: 'الكعكية', value: 'Al Kaeka' },
  { name: 'العسيلة', value: 'Al Asila' },
  { name: 'الضيافة', value: 'Al Deyafa' },
  { name: 'الشبيكة', value: 'Al Shabekah' },
  { name: 'الزاهر', value: 'Al Zaher' },
  { name: 'الخنساء', value: 'Al Khansa' },
  { name: 'الحرم', value: 'Al Haram' },
  { name: 'التيسير', value: 'Al Tayseer' },
  { name: 'البحيرات', value: 'Al Bohayrat' },
  { name: 'الراشدية', value: 'Al Rashidiya' },
  { name: 'جبل النور', value: 'Light mountain' },
  {
    name: 'شعب عامر وشعب علي',
    value: 'The people of Amer and the people of Ali',
  },
  { name: 'جرول', value: 'Grul' },
  { name: 'الهجلة', value: 'Al Hajla' },
  { name: 'النزهة', value: 'Al Nozha' },
  { name: 'المشاعر', value: 'Al Masher' },
  { name: 'القرارة والنقا', value: 'Qara and Naqa' },
  { name: 'العدل', value: 'Al Adl' },
  { name: 'السليمانية', value: 'Al Sulaymaniyah' },
  { name: 'الروضة', value: 'Al Rawdah' },
  { name: 'الخضراء', value: 'Al Khodra' },
  { name: 'الحجون', value: 'Al Hujun' },
  { name: 'التنعيم', value: 'Al Taneem' },
  { name: 'الأندلس', value: 'Al Andalous' },
  { name: 'الزايدي', value: 'Zaydi' },
  { name: 'ولي العهد', value: 'Wali Al Ahd' },
  { name: 'شرائع المجاهدين', value: 'Sharaea Al Mujahideen' },
  { name: 'السلام', value: 'Al Salam' },
  { name: 'الهجرة', value: 'Al Hegrah' },
  { name: 'المنصور', value: 'Al Mansour' },
  { name: 'المسفلة', value: 'Al Musfalah' },
  { name: 'العمرة الجديدة', value: 'Al Omra Al Gadedah' },
  { name: 'العتيبية', value: 'Al Otaiba' },
  { name: 'الشهداء', value: 'Al Shohada' },
  { name: 'السلامة', value: 'Al Salamah' },
  { name: 'الروابي', value: 'Al Rawaby' },
  { name: 'الخالدية', value: 'Al Kahedeyah' },
  { name: 'الجميزة', value: 'Al Gemezah' },
  { name: 'التقوى', value: 'Al Taqwa' },
  { name: 'اجياد', value: 'Agyad' },
];
