export const RiyadhNorth = [
  { name: 'ام الحمام الشرقي', value: 'Umm Al-Hammam Al-sharqi' },
  { name: 'المعذر الشمالي', value: 'North Maathar' },
  { name: 'السليمانية', value: 'Sulaymaniyah' },
  { name: 'الملك عبد العزيز', value: 'King Abdulaziz' },
  { name: 'الملك عبد الله', value: 'King Abdullah' },
  { name: 'الواحة', value: 'Al Waha' },
  { name: 'صالح الدين', value: 'Salah Al din' },
  { name: 'الورود', value: 'Roses' },
  { name: 'الرحمانية', value: 'Rahmaniyah' },
  { name: 'الرائد', value: 'Pioneer' },
  { name: 'الخزامى', value: 'lavender' },
  { name: 'حي جامعة الملك سعود', value: 'King Saud University District' },
  { name: 'المحمدية', value: 'Muhammadiyah' },
  { name: 'الملك فهد', value: 'King Fahd' },
  { name: 'المرسلات', value: 'Al-Mursalat' },
  { name: 'النزهة', value: 'Al Nozha' },
  { name: 'المغرزات', value: 'Al Mugharrat' },
  { name: 'الازدهار', value: 'prosperity' },
  { name: 'التعاون', value: 'Al Taawoon' },
  { name: 'المصيف', value: 'the resort' },
  { name: 'المروج', value: 'Al Morog' },
  { name: 'النخيل', value: 'Al Nakheel' },
  { name: 'الفلاح', value: 'Al Falah' },
  { name: 'الوادي', value: 'Al Wady' },
  { name: 'النفل', value: 'Al Naql' },
  { name: 'الغدير', value: 'Ghadir' },
  { name: 'العقيق', value: 'Al Aqeeq' },
  { name: 'حطين', value: 'Hittin' },
  {
    name: 'جامعة الامام محمد بن سعود الاسلامية',
    value: 'Imam Muhammad Bin Saud Islamic University',
  },
  { name: 'الندى', value: 'dew' },
  { name: 'الربيع', value: 'spring' },
  { name: 'الصحافة', value: 'the press' },
  { name: 'الملقا', value: 'Al-Malqa' },
  { name: 'حي المطار الملك خالد', value: 'Airport District, King Khaled' },
  { name: 'النرجس', value: 'Narcissus' },
  { name: 'العارض', value: 'renderer' },
  { name: 'القيروان', value: 'Kairouan' },
  { name: 'بنبان    ', value: 'Benban' },
  { name: 'الخير', value: 'The good' },
];

export const RiyadhSouth = [
  { name: 'ام الشعال', value: 'Umm Al-Shaal' },
  { name: 'الحائر', value: 'bewildered' },
  { name: 'عريض', value: 'wide' },
  { name: 'المصفاة', value: 'the filter' },
  { name: 'هيت', value: 'Hit' },
  { name: 'المدينة الصناعية الثانية', value: 'Second Industrial City' },
  { name: 'الغنامية', value: 'Ghanamia' },
  { name: 'المنصورية', value: 'Mansourieh' },
  { name: 'طيبة', value: 'Kind' },
  { name: 'بدر', value: 'Badr' },
  { name: 'عكاظ', value: 'Okaz' },
  { name: 'أحد', value: 'Uhud' },
  { name: 'المروة', value: 'Marwa' },
  { name: 'الاسكان', value: 'housing' },
  { name: 'الدفاع', value: 'Defense' },
  { name: 'الدار البيضاء', value: 'Casablanca' },
  { name: 'العزيزية', value: 'Azizia' },
  { name: 'المصانع', value: 'Factory' },
  { name: 'المناخ', value: 'Climate' },
  { name: 'النور', value: 'the light' },
  { name: 'الشفا', value: 'lip' },
  { name: 'عتيقة', value: 'antique' },
  { name: 'الدريهمية', value: 'Al -Duraiyah' },
  { name: 'صياح', value: 'shouting' },
  { name: 'سلطانة', value: 'Sultana' },
];

export const RiyadhEast = [
  { name: 'البرية', value: 'Al Bareya' },
  { name: 'المشاعل', value: 'Al Mashaeel' },
  { name: 'خشم العان', value: 'Khashm Al Aan' },
  { name: 'السلي', value: 'Al Salee' },
  { name: 'الجزيرة', value: 'Al Gazirah' },
  { name: 'السعادة', value: 'Al Saada' },
  { name: 'الفيحاء', value: 'Al Fayhaa' },
  { name: 'الروابي', value: 'Al Rawabe' },
  { name: 'السلام', value: 'Al Salam' },
  { name: 'الربوة', value: 'Al Rabwa' },
  { name: 'النسيم الغربي', value: 'Western Nassim' },
  { name: 'النسيم الشرقى', value: 'Eastern Nassim' },
  { name: 'النمار', value: 'Al Namar' },
  { name: 'الريان', value: 'Al Ryan' },
  { name: 'الرماية', value: 'Al Remaya' },
  { name: 'الندوة', value: 'Al Nadwa' },
  { name: 'النهضة', value: 'Al Nahda' },
  { name: 'الأندلس', value: 'Al Andalos' },
  { name: 'الروضة', value: 'Al Rwda' },
  { name: 'القدس', value: 'Al Quds' },
  { name: 'الملك فيصل', value: 'King Faisal' },
  { name: 'الخليج', value: 'Al Khaleeg' },
  { name: 'المعيزلة', value: 'Al Maaezlah' },
  { name: 'القادسية', value: 'Al Qadeseya' },
  { name: 'اشبيلية', value: 'Eshbeliya' },
  { name: 'اليرموك', value: 'Al Yarmook' },
  { name: 'الحمراء الشهداء', value: 'Al Hamraa El Shohadaa' },
  { name: 'المونسية', value: 'Almonsiyah' },
  { name: 'قرطبة', value: 'Cortoba' },
  { name: 'الرمال', value: 'El Remal' },
  { name: 'النظيم', value: 'Al Nazeem' },
  { name: 'الجنادرية', value: 'Janadriyah' },
  { name: 'الوسام', value: 'Al Wesaam' },
  { name: 'البيان', value: 'Al Bayan' },
  { name: 'المرجان', value: 'Al Morgan' },
  { name: 'السحاب', value: 'Al Sehab' },
  { name: 'المشرق', value: 'Al Mashreeq' },
  { name: 'الزاهر', value: 'Al Zaher' },
  { name: 'التضامن', value: 'Al Tadamon' },
  { name: 'العلا', value: 'Al Olaa' },
  { name: 'الشعلة', value: 'Al Shola' },
  { name: 'الراية', value: 'Al Raya' },
  { name: 'الفرسان', value: 'Al Forsan' },
  { name: 'النخبة', value: 'Al Nokhba' },
  { name: 'الدانة', value: 'Al Dana' },
  { name: 'الرسالة', value: 'Al Resala' },
  { name: 'المجد', value: 'Al Magd' },
  { name: 'الرحاب', value: 'Al Rehab' },
];

export const RiyadhWest = [
  { name: 'مدينة الملك عبد الله للطاقة', value: 'King Abdullah Energy City' },
  { name: 'ضاحية نمار', value: 'Namar suburb' },
  { name: 'ديراب', value: 'Dirab' },
  { name: 'الحزم', value: 'Al Hazm' },
  { name: 'نمار', value: 'Namar' },
  { name: 'العوالي', value: 'Awali' },
  { name: 'طويق', value: 'Taweek' },
  { name: 'وادي لبن', value: 'Laban Valley' },
  { name: 'ظهرة لبن', value: 'Dhahrat Laban' },
  { name: 'المهدية', value: 'Mahdia' },
  { name: 'العريجاء', value: 'Al-Araija' },
  { name: 'السويدي الغربي', value: 'Western Swedish' },
  { name: 'لبن', value: 'leben' },
  { name: 'شبرا', value: 'shobra' },
  { name: 'السويدي', value: 'Swedish' },
  { name: 'الزهرة', value: 'Al-Zahra' },
  { name: 'ظهرة البديعة', value: "Badia's back" },
  { name: 'العريجاء الوسطى', value: 'Al-Araija Al-Wusta' },
  { name: 'البديعة', value: 'the beauty' },
  { name: 'عليشة', value: 'Aisha' },
  { name: 'الفاخرية', value: 'luxury' },
  { name: 'الناصرية', value: 'Nasiriyah' },
  { name: 'الرفيعة', value: 'Al Rafeah' },
  { name: 'المعذر', value: 'Al Mazer' },
  { name: 'الشرفية', value: 'Al Sharfeya' },
  { name: 'الهدا', value: 'Al Huda' },
  { name: 'الفارات', value: 'the ferrets' },
  { name: 'ام الحمام الغربي', value: 'Umm al-Hammam al-Gharbi' },
];

export const RiyadhMiddle = [
  { name: 'الفيصلية', value: 'Al Faisaliyah' },
  { name: 'الخالدية', value: 'Khalidiya' },
  { name: 'المنصورة', value: 'Mansoura' },
  { name: 'اليمامة', value: 'Al-Yamamah' },
  { name: 'غبيرة', value: 'Gabera' },
  { name: 'منفحة الجديدة', value: 'Manfaha El Gadeda' },
  { name: 'الفاروق', value: 'Al Farouk' },
  { name: 'الصناعية', value: 'Al Senaeyaa' },
  { name: 'الصالحية', value: 'Al Salhia' },
  { name: 'العود', value: 'Al Oud' },
  { name: 'جبرة', value: 'Gebra' },
  { name: 'الدويبة', value: 'Al Duwaibeh' },
  { name: 'الجرادية', value: 'Al Gradyah' },
  { name: 'الشميسي', value: 'Al Shumaisi' },
  { name: 'ام سليم', value: 'Umm Selim' },
  { name: 'الوشام', value: 'Al Wesham' },
  { name: 'العمل', value: 'Al Amal' },
  { name: 'ثليم', value: 'Thulme' },
  { name: 'المرقب', value: 'Al Marqb' },
  { name: 'الملز', value: 'Al Malaz' },
  { name: 'المربع', value: 'Al Morabaa' },
  { name: 'النموذجية', value: 'Al Namozageya' },
  { name: 'المؤتمرات', value: 'Al Moatamarat' },
  { name: 'الوزارات', value: 'Al Wezarat' },
  { name: 'الضباط', value: 'Al Zobaat' },
  { name: 'الزهراء', value: 'Al Zahraa' },
  { name: 'جرير', value: 'Garer' },
  { name: 'الصفا', value: 'Al Safa' },
];
